# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(520, 420)
        window.setMinimumSize(QtCore.QSize(520, 420))
        window.setMaximumSize(QtCore.QSize(520, 420))
        window.setStyleSheet("")
        self.btn_next = QtWidgets.QPushButton(window)
        self.btn_next.setGeometry(QtCore.QRect(450, 350, 50, 50))
        self.btn_next.setToolTipDuration(-1)
        self.btn_next.setText("")
        self.btn_next.setObjectName("btn_next")
        self.btn_word = QtWidgets.QPushButton(window)
        self.btn_word.setGeometry(QtCore.QRect(36, 50, 441, 80))
        self.btn_word.setToolTipDuration(-1)
        self.btn_word.setFlat(False)
        self.btn_word.setObjectName("btn_word")
        self.label_phonetic = QtWidgets.QLabel(window)
        self.label_phonetic.setGeometry(QtCore.QRect(1, 120, 520, 41))
        self.label_phonetic.setTextFormat(QtCore.Qt.PlainText)
        self.label_phonetic.setAlignment(QtCore.Qt.AlignCenter)
        self.label_phonetic.setObjectName("label_phonetic")
        self.textEdit_explant = QtWidgets.QTextEdit(window)
        self.textEdit_explant.setGeometry(QtCore.QRect(20, 180, 501, 161))
        self.textEdit_explant.setReadOnly(True)
        self.textEdit_explant.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Bahnschrift SemiBold SemiConden\'; font-size:12pt;\">int. 喂；哈罗，你好，您好 </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Bahnschrift SemiBold SemiConden\'; font-size:12pt;\">n. 表示问候， 惊奇或唤起注意时的用语 </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Bahnschrift SemiBold SemiConden\'; font-size:12pt;\">n. (Hello) 人名；（法）埃洛</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Bahnschrift SemiBold SemiConden\'; font-size:12pt;\">int. 喂；哈罗，你好，您好 </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Bahnschrift SemiBold SemiConden\'; font-size:12pt;\">n. 表示问候， 惊奇或唤起注意时的用语 </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Bahnschrift SemiBold SemiConden\'; font-size:12pt;\">n. (Hello) 人名；（法）埃洛</span></p></body></html>")
        self.textEdit_explant.setPlaceholderText("")
        self.textEdit_explant.setObjectName("textEdit_explant")
        self.btn_close = QtWidgets.QPushButton(window)
        self.btn_close.setGeometry(QtCore.QRect(490, 10, 20, 20))
        self.btn_close.setObjectName("btn_close")
        self.btn_refresh = QtWidgets.QPushButton(window)
        self.btn_refresh.setGeometry(QtCore.QRect(456, 14, 17, 17))
        self.btn_refresh.setText("")
        self.btn_refresh.setObjectName("btn_refresh")

        self.retranslateUi(window)
        self.btn_next.clicked.connect(window.next_word)
        self.btn_word.clicked.connect(window.read_word)
        self.btn_refresh.clicked.connect(window.refresh_word)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "Form"))
        self.btn_next.setToolTip(_translate("window", "下一个单词"))
        self.btn_word.setText(_translate("window", "hello"))
        self.label_phonetic.setText(_translate("window", "[həˈləʊ]"))
        self.btn_close.setToolTip(_translate("window", "退出"))
        self.btn_close.setText(_translate("window", "×"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QWidget()
    ui = Ui_window()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec_())
